#!/usr/bin/env python3
"""Generate exact Unicode Bidi_Class R/AL membership runs as Swift source."""

from __future__ import annotations

import argparse
import pathlib
import re


SCALAR_COUNT = 0x110000
RANGE = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?$")
BIDI_CLASSES = {
    "AL",
    "AN",
    "Arabic_Letter",
    "Arabic_Number",
    "B",
    "BN",
    "Boundary_Neutral",
    "CS",
    "Common_Separator",
    "EN",
    "ES",
    "ET",
    "European_Number",
    "European_Separator",
    "European_Terminator",
    "FSI",
    "First_Strong_Isolate",
    "L",
    "LRE",
    "LRI",
    "LRO",
    "Left_To_Right",
    "Left_To_Right_Embedding",
    "Left_To_Right_Isolate",
    "Left_To_Right_Override",
    "NSM",
    "Nonspacing_Mark",
    "ON",
    "Other_Neutral",
    "PDF",
    "PDI",
    "Paragraph_Separator",
    "Pop_Directional_Format",
    "Pop_Directional_Isolate",
    "R",
    "RLE",
    "RLI",
    "RLO",
    "Right_To_Left",
    "Right_To_Left_Embedding",
    "Right_To_Left_Isolate",
    "Right_To_Left_Override",
    "S",
    "Segment_Separator",
    "WS",
    "White_Space",
}


def scalar_range(value: str) -> tuple[int, int]:
    match = RANGE.fullmatch(value)
    if match is None:
        raise ValueError(f"invalid scalar range: {value}")
    lower = int(match.group(1), 16)
    upper = int(match.group(2) or match.group(1), 16)
    if lower > upper:
        raise ValueError(f"reversed scalar range: {value}")
    if upper >= SCALAR_COUNT:
        raise ValueError(f"scalar range outside Unicode: {value}")
    return lower, upper


def class_value(name: str) -> int:
    if name not in BIDI_CLASSES:
        raise ValueError(f"unknown bidi property: {name}")
    return 1 if name in {"R", "Right_To_Left"} else 2 if name in {"AL", "Arabic_Letter"} else 0


def property_record(value: str) -> tuple[str, str]:
    fields = value.split(";")
    if len(fields) != 2 or not all(field.strip() for field in fields):
        raise ValueError(f"malformed bidi property record: {value}")
    return fields[0].strip(), fields[1].strip()


def apply(classes: bytearray, span: str, bidi_class: str) -> None:
    lower, upper = scalar_range(span)
    value = class_value(bidi_class)
    classes[lower : upper + 1] = bytes([value]) * (upper - lower + 1)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    arguments = parser.parse_args()

    lines = arguments.source.read_text(encoding="utf-8").splitlines()
    classes = bytearray(SCALAR_COUNT)

    for raw_line in lines:
        line = raw_line.strip()
        if line.startswith("# @missing:"):
            body = line.removeprefix("# @missing:").split("#", 1)[0].strip()
            span, bidi_class = property_record(body)
            apply(classes, span, bidi_class)

    for raw_line in lines:
        body = raw_line.split("#", 1)[0].strip()
        if not body:
            continue
        span, bidi_class = property_record(body)
        apply(classes, span, bidi_class)

    runs: list[tuple[int, int]] = []
    start: int | None = None
    for scalar, value in enumerate(classes):
        if value and start is None:
            start = scalar
        elif not value and start is not None:
            runs.append((start, scalar - 1))
            start = None
    if start is not None:
        runs.append((start, SCALAR_COUNT - 1))

    body = "\n".join(f"    (0x{lower:X}, 0x{upper:X})," for lower, upper in runs)
    output = f"""// Generated by Scripts/generate_unicode_bidi.sh. Do not edit.
//
// Source: Unicode 15.1.0 DerivedBidiClass.txt, Bidi_Class R and AL.
// Source SHA-256: b57884c59a3a5348d86faed39965bbddb4e4493d3c16c1ec378ec26bfb5821be

enum MermaidUnicodeBidiData {{
  static func isStrongRightToLeft(_ scalar: UInt32) -> Bool {{
    var lower = 0
    var upper = runs.count
    while lower < upper {{
      let middle = lower + (upper - lower) / 2
      let run = runs[middle]
      if scalar < run.0 {{
        upper = middle
      }} else if scalar > run.1 {{
        lower = middle + 1
      }} else {{
        return true
      }}
    }}
    return false
  }}

  private static let runs: [(UInt32, UInt32)] = [
{body}
  ]
}}
"""
    arguments.output.write_text(output, encoding="utf-8")
    print(f"wrote {arguments.output} ({len(runs)} runs)")


if __name__ == "__main__":
    main()
