#!/usr/bin/env python3
"""Convert width-oracle runs on stdin to checked-in Swift source."""

from __future__ import annotations

import argparse
import pathlib
import sys


SCALAR_MAX = 0x10FFFF


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=pathlib.Path)
    arguments = parser.parse_args()

    runs: list[tuple[int, int, int, int]] = []
    for raw_line in sys.stdin:
        line = raw_line.strip()
        if not line:
            continue
        lower, upper, normal, cjk = line.split()
        run = (int(lower, 16), int(upper, 16), int(normal), int(cjk))
        if not 0 <= run[0] <= SCALAR_MAX or not 0 <= run[1] <= SCALAR_MAX:
            raise ValueError(f"width run outside Unicode: {line}")
        if run[0] > run[1]:
            raise ValueError(f"reversed width run: {line}")
        if run[2] not in {0, 1, 2, 3} or run[3] not in {0, 1, 2, 3}:
            raise ValueError(f"unsupported width value: {line}")
        runs.append(run)

    if not runs:
        raise ValueError("width run stream is empty")
    if runs[0][0] != 0:
        raise ValueError("width runs must start at U+0000")
    if any(current[0] < previous[0] for previous, current in zip(runs, runs[1:])):
        raise ValueError("width runs are unsorted")
    if any(current[0] <= previous[1] for previous, current in zip(runs, runs[1:])):
        raise ValueError("width runs overlap")
    if any(current[0] != previous[1] + 1 for previous, current in zip(runs, runs[1:])):
        raise ValueError("width runs contain a gap")
    if runs[-1][1] != SCALAR_MAX:
        raise ValueError("width runs must end at U+10FFFF")

    body = "\n".join(
        f"    (0x{lower:X}, 0x{upper:X}, {normal}, {cjk}),"
        for lower, upper, normal, cjk in runs
    )
    source = f"""// Generated by Scripts/generate_unicode_width.sh. Do not edit.
//
// Source: unicode-width 0.2.0, pinned in Tools/width-oracle/Cargo.lock.
// Each tuple is (lower scalar, upper scalar, normal width, CJK width).

enum MermaidUnicodeWidthData {{
  static func width(of scalar: UInt32, policy: MermaidAmbiguousWidth) -> Int {{
    var lower = 0
    var upper = runs.count
    while lower < upper {{
      let middle = lower + (upper - lower) / 2
      let run = runs[middle]
      if scalar < run.0 {{
        upper = middle
      }} else if scalar > run.1 {{
        lower = middle + 1
      }} else {{
        return policy == .wide ? run.3 : run.2
      }}
    }}
    return 1
  }}

  private static let runs: [(UInt32, UInt32, Int, Int)] = [
{body}
  ]
}}
"""
    arguments.output.write_text(source, encoding="utf-8")
    print(f"wrote {arguments.output} ({len(runs)} runs)")


if __name__ == "__main__":
    main()
