import Foundation
import Testing

@testable import GIFEditorCore

/// The `formatVersion: 1` file that must keep decoding forever.
///
/// It is checked in, small enough to read by eye, and deliberately *not*
/// regenerated by the test suite: the whole point is that today's reader
/// is held against bytes written by an older one. If a change to the
/// format makes this file fail to decode, the change needs a
/// `formatVersion` bump and a migration path, not a new fixture.
///
/// There is no "fixture missing, skip" branch here on purpose. The
/// suite has been bitten before by a `#filePath` walk that went one
/// directory too far and turned two tests into silent no-ops, so a
/// missing fixture fails: `Data(contentsOf:)` throws and the test with
/// it.
@Suite("Project file — golden v1 fixture")
struct ProjectFileGoldenTests {

  /// Resolved relative to this source file rather than the working
  /// directory. The package declares no test resources, so `Fixtures/`
  /// sits beside `Sources/` and `Tests/` at the package root.
  static var goldenURL: URL {
    let here = URL(fileURLWithPath: #filePath)
    return
      here
      .deletingLastPathComponent()  // Tests/GIFEditorCoreTests/
      .deletingLastPathComponent()  // Tests/
      .deletingLastPathComponent()  // <package root>/
      .appendingPathComponent("Fixtures")
      .appendingPathComponent("project-v1-golden.halfcell")
  }

  /// Exactly what the checked-in file encodes. Fixed UUIDs so the
  /// identity assertions are about the file, not about this run.
  static func expectedDocument() -> GIFDocument {
    let size = PixelSize(width: 4, height: 4)
    let palette = ColorPalette(colors: [
      .transparent,
      EditorColor(rgbHex: 0xFF005D),
      EditorColor(rgbHex: 0x00C896),
      EditorColor(rgbHex: 0xC0FF33),
      EditorColor(red: 12, green: 34, blue: 56, alpha: 78),
    ])

    var background = PixelBuffer(size: size)
    for x in 0..<4 { background[PixelPoint(x: x, y: 0)] = 1 }
    background[PixelPoint(x: 3, y: 3)] = 4

    var foreground = PixelBuffer(size: size)
    foreground[PixelPoint(x: 1, y: 1)] = 2
    foreground[PixelPoint(x: 2, y: 2)] = 3

    let frameOne = EditorFrame(
      id: UUID(uuidString: "11111111-1111-4111-8111-111111111111")!,
      layers: [
        EditorLayer(
          id: UUID(uuidString: "AAAAAAAA-0000-4000-8000-000000000001")!,
          name: "Background",
          isVisible: true,
          pixels: background
        ),
        EditorLayer(
          id: UUID(uuidString: "AAAAAAAA-0000-4000-8000-000000000002")!,
          name: "Sparkle",
          isVisible: false,
          pixels: foreground
        ),
      ],
      delayCentiseconds: 7,
      disposal: .keep
    )

    let frameTwo = EditorFrame(
      id: UUID(uuidString: "22222222-2222-4222-8222-222222222222")!,
      layers: [
        EditorLayer(
          id: UUID(uuidString: "BBBBBBBB-0000-4000-8000-000000000001")!,
          name: "Background",
          isVisible: true,
          pixels: foreground
        ),
        EditorLayer(
          id: UUID(uuidString: "BBBBBBBB-0000-4000-8000-000000000002")!,
          name: "Sparkle",
          isVisible: true,
          pixels: background
        ),
      ],
      delayCentiseconds: 13,
      disposal: .previous
    )

    return GIFDocument(
      size: size,
      palette: palette,
      frames: [frameOne, frameTwo],
      loopCount: 3
    )
  }

  @Test("The checked-in v1 fixture still decodes, field for field")
  func goldenFileDecodes() throws {
    let url = Self.goldenURL
    #expect(
      FileManager.default.fileExists(atPath: url.path),
      "golden fixture missing at \(url.path); it must not be deleted or regenerated"
    )
    let data = try Data(contentsOf: url)
    let decoded = try ProjectFile.document(from: data)
    let expected = Self.expectedDocument()

    #expect(decoded.size == expected.size)
    #expect(decoded.loopCount == expected.loopCount)
    #expect(decoded.palette.usedCount == expected.palette.usedCount)
    #expect(decoded.palette.usedColors == expected.palette.usedColors)
    #expect(decoded.frames.count == expected.frames.count)

    for (frameIndex, expectedFrame) in expected.frames.enumerated() {
      guard frameIndex < decoded.frames.count else { break }
      let frame = decoded.frames[frameIndex]
      #expect(frame.id == expectedFrame.id, "frame \(frameIndex) id")
      #expect(
        frame.delayCentiseconds == expectedFrame.delayCentiseconds, "frame \(frameIndex) delay")
      #expect(frame.disposal == expectedFrame.disposal, "frame \(frameIndex) disposal")
      #expect(frame.layers.count == expectedFrame.layers.count, "frame \(frameIndex) layers")

      for (layerIndex, expectedLayer) in expectedFrame.layers.enumerated() {
        guard layerIndex < frame.layers.count else { break }
        let layer = frame.layers[layerIndex]
        let label = "frame \(frameIndex) layer \(layerIndex)"
        #expect(layer.id == expectedLayer.id, "\(label) id")
        #expect(layer.name == expectedLayer.name, "\(label) name")
        #expect(layer.isVisible == expectedLayer.isVisible, "\(label) visibility")
        #expect(layer.pixels.pixels == expectedLayer.pixels.pixels, "\(label) pixels")
      }
    }

    #expect(decoded == expected)
  }

  @Test("The fixture is a version 1 envelope and carries no authoring path")
  func goldenFileIsVersionOne() throws {
    let data = try Data(contentsOf: Self.goldenURL)
    let object = try JSONSerialization.jsonObject(with: data)
    let envelope = try #require(object as? [String: Any])
    #expect(envelope["formatVersion"] as? Int == 1)
    let document = try #require(envelope["document"] as? [String: Any])
    #expect(document["path"] == nil)
    #expect(!String(decoding: data, as: UTF8.self).contains("/Users/"))
  }

  @Test("Today's encoder still produces the checked-in bytes")
  func encoderStillMatchesTheFixture() throws {
    // Not a requirement of the format — only the *decode* must hold
    // forever — but while it is true it is the cheapest possible
    // warning that an encoder change altered the wire shape.
    let data = try Data(contentsOf: Self.goldenURL)
    #expect(try ProjectFile.data(for: Self.expectedDocument()) == data)
  }
}
