import Foundation
import SwiftParser
import SwiftSyntax

@main
struct LayoutSnippetGenerator {
  static func main() throws {
    let arguments = Array(CommandLine.arguments.dropFirst())
    guard
      arguments.count >= 3,
      arguments.first == "--output"
    else {
      throw GenerationError.usage
    }

    let outputURL = URL(fileURLWithPath: arguments[1])
    let sourceURLs = arguments.dropFirst(2).map { URL(fileURLWithPath: $0) }
    let output = try GeneratedSnippets(sourceURLs: sourceURLs).render()

    try FileManager.default.createDirectory(
      at: outputURL.deletingLastPathComponent(),
      withIntermediateDirectories: true
    )
    try output.write(to: outputURL, atomically: true, encoding: .utf8)
  }
}

private struct GeneratedSnippets {
  let sourceURLs: [URL]

  func render() throws -> String {
    var entriesByID: [String: String] = [:]
    var snippetsByTypeName: [String: String] = [:]

    for sourceURL in sourceURLs.sorted(by: { $0.path < $1.path }) {
      let source = try String(contentsOf: sourceURL, encoding: .utf8)
      let tree = Parser.parse(source: source)
      let collector = LayoutSourceCollector(viewMode: .sourceAccurate)
      collector.walk(tree)

      let snippet = displaySnippet(from: source)
      for structName in collector.structNames {
        snippetsByTypeName[structName] = snippet
      }
      entriesByID.merge(collector.entriesByID) { current, _ in current }
    }

    var snippetsByID: [String: String] = [:]
    var missing: [String] = []
    for (id, typeName) in entriesByID {
      guard let snippet = snippetsByTypeName[typeName] else {
        missing.append("\(id) -> \(typeName)")
        continue
      }
      snippetsByID[id] = snippet
    }

    if !missing.isEmpty {
      throw GenerationError.missingSnippets(missing.sorted())
    }

    return renderSwiftSource(snippetsByID: snippetsByID)
  }

  private func displaySnippet(from source: String) -> String {
    source.trimmingCharacters(in: .whitespacesAndNewlines)
  }

  private func renderSwiftSource(snippetsByID: [String: String]) -> String {
    var result = """
      // Generated by LayoutSourceSnippetPlugin. Do not edit directly.

      public enum LayoutSourceSnippets {
        public static let byID: [String: String] = [

      """

    for id in snippetsByID.keys.sorted() {
      guard let snippet = snippetsByID[id] else {
        continue
      }
      result += "    \(swiftStringLiteral(id)): \(swiftMultilineStringLiteral(snippet)),\n"
    }

    result += """
        ]
      }

      """

    return result
  }

  private func swiftStringLiteral(_ value: String) -> String {
    String(reflecting: value)
  }

  private func swiftMultilineStringLiteral(_ value: String) -> String {
    var hashes = "#"
    while value.contains("\"\"\"\(hashes)") {
      hashes += "#"
    }

    return "\(hashes)\"\"\"\n\(value)\n\"\"\"\(hashes)"
  }
}

private final class LayoutSourceCollector: SyntaxVisitor {
  var entriesByID: [String: String] = [:]
  var structNames: Set<String> = []

  override func visit(_ node: StructDeclSyntax) -> SyntaxVisitorContinueKind {
    structNames.insert(node.name.text)
    return .skipChildren
  }

  override func visit(_ node: FunctionCallExprSyntax) -> SyntaxVisitorContinueKind {
    guard node.calledExpression.trimmedDescription == "LayoutEntry" else {
      return .visitChildren
    }

    var id: String?
    var makeViewExpression: ExprSyntax?

    for argument in node.arguments {
      switch argument.label?.text {
      case "id":
        id = stringLiteralValue(argument.expression)
      case "makeView":
        makeViewExpression = argument.expression
      default:
        break
      }
    }

    if
      let id,
      let makeViewExpression,
      let typeName = makeViewTypeName(in: makeViewExpression)
    {
      entriesByID[id] = typeName
    }

    return .skipChildren
  }

  private func stringLiteralValue(_ expression: ExprSyntax) -> String? {
    let text = expression.trimmedDescription
    guard text.first == "\"", text.last == "\"" else {
      return nil
    }

    return String(text.dropFirst().dropLast())
  }

  private func makeViewTypeName(in expression: ExprSyntax) -> String? {
    let visitor = AnyViewTypeCollector(viewMode: .sourceAccurate)
    visitor.walk(Syntax(expression))
    return visitor.typeName
  }
}

private final class AnyViewTypeCollector: SyntaxVisitor {
  var typeName: String?

  override func visit(_ node: FunctionCallExprSyntax) -> SyntaxVisitorContinueKind {
    guard typeName == nil else {
      return .skipChildren
    }

    guard
      node.calledExpression.trimmedDescription == "AnyView",
      let viewInitializer = node.arguments.first?.expression.as(FunctionCallExprSyntax.self)
    else {
      return .visitChildren
    }

    typeName = viewInitializer.calledExpression.trimmedDescription
      .split(separator: ".")
      .last
      .map(String.init)
    return .skipChildren
  }
}

private enum GenerationError: Error, CustomStringConvertible {
  case usage
  case missingSnippets([String])

  var description: String {
    switch self {
    case .usage:
      return "usage: LayoutSnippetGenerator --output <path> <swift-source>..."
    case .missingSnippets(let entries):
      return "missing layout source snippets for: \(entries.joined(separator: ", "))"
    }
  }
}
