#!/usr/bin/env sh
#
# Records the test fixtures in Tests/GitVizTests/Fixtures from a real `git`.
#
# Builds a throwaway repository containing the shapes that actually break
# parsers — a merge (which emits no numstat block), a rename (which emits a
# three-token NUL entry), a unicode subject, and both annotated and
# lightweight tags — then runs the exact argv `GitRepo` issues and writes the
# raw bytes out.
#
# Commit dates are pinned, so re-running produces byte-identical fixtures
# unless git's output format itself changes. That is the point: a diff here
# means git changed, not that the clock moved.
#
# Usage:  Scripts/record_git_fixtures.sh

set -eu

package_root=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
fixtures="$package_root/Tests/GitVizTests/Fixtures"

if ! command -v git >/dev/null 2>&1; then
  echo "Missing required command: git" >&2
  exit 1
fi

git_version=$(git --version)

# ASCII record / unit separators, matching GitParsers.recordSeparator and
# GitParsers.fieldSeparator.
RS=$(printf '\036')
US=$(printf '\037')

log_format="%H${US}%aI${US}%aN${US}%aE${US}%P${US}%s"
tag_format="%(refname:short)${US}%(objectname)${US}%(taggerdate:iso-strict)${US}%(committerdate:iso-strict)${US}%(objecttype)${RS}"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

cd "$work"
git init -q -b main .
git config user.name "Alice Cooper"
git config user.email "alice@example.com"
git config commit.gpgsign false

# Pinned identity + clock. Every commit advances the stamp by one day so the
# ordering is meaningful without being wall-clock dependent.
stamp_day=1
commit() {
  subject=$1
  date="2020-01-0${stamp_day}T09:00:00+00:00"
  GIT_AUTHOR_DATE="$date" GIT_COMMITTER_DATE="$date" \
    git commit -q -m "$subject"
  stamp_day=$((stamp_day + 1))
}

# 1. Two ordinary commits by the first author.
printf 'one\n' >a.txt
git add a.txt
commit "feat: add the first file"

printf 'one\ntwo\n' >a.txt
git add a.txt
commit "fix: correct the first file"

# 2. A side branch, so the merge below is a real two-parent commit.
git checkout -q -b side
printf 'side\n' >b.txt
git add b.txt
commit "chore: add a side file"

# 3. A second author, so shortlog has more than one row.
git checkout -q main
git config user.name "Bob Dylan"
git config user.email "bob@example.com"
printf 'unicode\n' >c.txt
git add c.txt
commit "docs: café ünïcode subject — em dash and é"

# 4. A merge commit. Emits NO numstat block, which is the shape that used to
#    be absent from every fixture.
merge_date="2020-01-0${stamp_day}T09:00:00+00:00"
GIT_AUTHOR_DATE="$merge_date" GIT_COMMITTER_DATE="$merge_date" \
  git merge -q --no-ff side -m "Merge branch 'side' into main"
stamp_day=$((stamp_day + 1))

# 5. A rename. Under -z this emits `0\t0\0<old>\0<new>\0` — three NUL tokens
#    for one entry.
git mv a.txt renamed.txt
commit "refactor: rename the first file"

# 6. Both tag kinds: annotated carries its own taggerdate and objecttype=tag.
tag_date="2020-02-01T09:00:00+00:00"
GIT_AUTHOR_DATE="$tag_date" GIT_COMMITTER_DATE="$tag_date" \
  git tag -a v1.0.0 -m "Release 1.0.0"
git tag v1.1.0

mkdir -p "$fixtures"

record() {
  name=$1
  shift
  printf '  %-24s git %s\n' "$name" "$*"
  git "$@" >"$fixtures/$name"
}

echo "==> Recording fixtures into $fixtures"
record log-numstat.txt \
  log --no-color -z --pretty="format:${RS}${log_format}" --numstat
record shortlog.txt \
  shortlog -s -n -e HEAD
record for-each-ref-tags.txt \
  for-each-ref refs/tags --format="$tag_format"
record rev-list-parents.txt \
  rev-list --topo-order --parents --max-count=200 HEAD
record name-only.txt \
  log --no-color --diff-filter=AMD --name-only --pretty="format:${RS}"

# Provenance lives beside the fixtures rather than inside them, so the
# recorded payloads stay byte-exact.
cat >"$fixtures/PROVENANCE.md" <<EOF
# Fixture provenance

Generated by \`Scripts/record_git_fixtures.sh\` — do not hand-edit. Re-run the
script to refresh; a diff means git's output format changed.

- Recorded with: \`$git_version\`
- Source: a throwaway repository built by the script, with pinned commit dates
  (2020-01-01 onward) so recordings are reproducible.

The repository deliberately contains a merge commit (emits no numstat block),
a rename (emits a three-token NUL entry under \`-z\`), a unicode subject, two
authors, and both an annotated and a lightweight tag.

| Fixture | argv |
| --- | --- |
| \`log-numstat.txt\` | \`log --no-color -z --pretty=format:<RS><logFormat> --numstat\` |
| \`shortlog.txt\` | \`shortlog -s -n -e HEAD\` |
| \`for-each-ref-tags.txt\` | \`for-each-ref refs/tags --format=<tagFormat>\` |
| \`rev-list-parents.txt\` | \`rev-list --topo-order --parents --max-count=200 HEAD\` |
| \`name-only.txt\` | \`log --no-color --diff-filter=AMD --name-only --pretty=format:<RS>\` |

\`<RS>\` is ASCII 0x1E and \`<logFormat>\`/\`<tagFormat>\` are the constants in
\`GitParsers\`; the script builds them from the same bytes.
EOF

echo "==> done."
