version = 1

[theme]
background = "#272822"
foreground = "#F8F8F2"
muted = "#75715E"
accent = "#A6E22E"
selection_background = "#49483E"
heading_1 = "#F92672"
heading_2 = "#FD971F"
heading_3 = "#E6DB74"
heading_4 = "#A6E22E"
heading_5 = "#66D9EF"
heading_6 = "#AE81FF"
link = "#66D9EF"
quote = "#75715E"
code_foreground = "#F8F8F2"
code_background = "#3E3D32"
table_border = "#75715E"
rule = "#75715E"
search_match = "#E6DB74"
error = "#F92672"
